# Stage 1: Multimodal Representation Learning Configuration
# 多模态表征学习阶段配置文件

# 数据参数
data_params:
  dataset_path: "data/representation_dataset"  # 表征学习数据集路径
  train_split: 0.8
  val_split: 0.2
  batch_size: 64
  num_workers: 8
  pin_memory: true
  
# 模型参数
model_params:
  # 视觉编码器参数
  vision_encoder:
    model_name: "vit_base_patch16_224"
    pretrained_weights_path: "checkpoints/stage0_vision_finetune/best_model.pth"  # 阶段0.5的权重
    freeze_encoder: false  # 是否冻结视觉编码器
    
  # 触觉编码器参数
  tactile_encoder:
    feature_dim: 54      # 18传感器 x 3轴 = 54维
    seq_len: 100         # 序列长度
    d_model: 768         # Transformer内部维度
    nhead: 12            # 多头注意力头数
    num_layers: 6        # Transformer层数
    dim_feedforward: 3072  # 前馈网络维度
    dropout: 0.1
    
  # 投影头参数
  projection:
    embed_dim: 128           # 共享嵌入空间维度
    projection_hidden_dim: 768  # 投影头隐藏层维度
    
# 训练参数
training_params:
  epochs: 100
  learning_rate: 1e-4
  weight_decay: 0.01
  optimizer: "adamw"
  warmup_epochs: 10
  
# 损失函数参数
loss_params:
  type: "infonce"
  temperature: 0.07  # 温度系数τ

# 多任务训练参数（新增）
multi_task_params:
  # InfoNCE损失权重，MSE预测损失权重为 (1 - alpha)
  # alpha = 1.0 等同纯对比学习；alpha = 0.0 等同纯预测
  alpha: 0.5
  
# 学习率调度器参数
scheduler_params:
  type: "cosine"
  T_max: 100
  eta_min: 1e-6
  
# 采样器参数
sampler_params:
  type: "balanced_batch"
  samples_per_class: 8  # 每个类别的样本数，确保负样本多样性
  
# 数据增强参数
augmentation_params:
  # 视觉增强
  vision:
    resize: [224, 448]  # 双目图像水平拼接后的尺寸
    random_crop: [224, 224]
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.05
    gaussian_blur:
      kernel_size: 3
      sigma: [0.1, 1.0]
    random_horizontal_flip: 0.5
    
  # 触觉增强
  tactile:
    gaussian_noise:
      std: 0.01
    random_scale:
      scale_range: [0.95, 1.05]
      
# 检查点参数
checkpoint_params:
  output_dir: "checkpoints/stage1_representation"
  save_freq: 20
  save_best: true
  
# 日志参数
logging_params:
  log_freq: 10
  tensorboard_dir: "logs/stage1_representation"
  
# 评估参数
evaluation_params:
  eval_freq: 5  # 每5个epoch评估一次
  metrics: ["loss", "accuracy", "retrieval_recall@1", "retrieval_recall@5"]
  
# 设备参数
device_params:
  use_cuda: true
  mixed_precision: true